/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.calculator;
import javax.swing.JButton;

/**
 *
 * @author KULAKSIZ
 */
public class CalculatorUI extends javax.swing.JFrame {

    private boolean m_zeroFlag;
    private boolean m_negativeFlag;
    private boolean m_pointFlag;
    private boolean m_operationFlag;
    private double  m_result;
    private char    m_lastOperator;
    /**
     * Creates new form CalculatorUI
     */
    public CalculatorUI() {
        initComponents();
        m_zeroFlag = true;
        m_negativeFlag = false;
        m_pointFlag = false;
        m_operationFlag = false;
        m_lastOperator = '=';
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_JButtonPlusMinus = new javax.swing.JButton();
        m_JButton0 = new javax.swing.JButton();
        m_JButtonPoint = new javax.swing.JButton();
        m_JButtonEqual = new javax.swing.JButton();
        m_JButton1 = new javax.swing.JButton();
        m_JButton2 = new javax.swing.JButton();
        m_JButton3 = new javax.swing.JButton();
        m_JButtonPlus = new javax.swing.JButton();
        m_JButton4 = new javax.swing.JButton();
        m_JButton5 = new javax.swing.JButton();
        m_JButton6 = new javax.swing.JButton();
        m_JButtonMinus = new javax.swing.JButton();
        m_JButton7 = new javax.swing.JButton();
        m_JButton8 = new javax.swing.JButton();
        m_JButton9 = new javax.swing.JButton();
        m_JButtonMultiply = new javax.swing.JButton();
        m_JButtonSquare = new javax.swing.JButton();
        m_JButtonClear = new javax.swing.JButton();
        m_JButtonRemainder = new javax.swing.JButton();
        m_JButtonDivide = new javax.swing.JButton();
        m_JScrollPane = new javax.swing.JScrollPane();
        m_JTextPaneResult = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        m_JButtonPlusMinus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButtonPlusMinus.setText("±");
        m_JButtonPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButtonPlusMinusActionPerformed(evt);
            }
        });

        m_JButton0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButton0.setText("0");
        m_JButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButton0ActionPerformed(evt);
            }
        });

        m_JButtonPoint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButtonPoint.setText(".");
        m_JButtonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButtonPointActionPerformed(evt);
            }
        });

        m_JButtonEqual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButtonEqual.setText("=");
        m_JButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButtonEqualActionPerformed(evt);
            }
        });

        m_JButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButton1.setText("1");
        m_JButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButton1ActionPerformed(evt);
            }
        });

        m_JButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButton2.setText("2");
        m_JButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButton2ActionPerformed(evt);
            }
        });

        m_JButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButton3.setText("3");
        m_JButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButton3ActionPerformed(evt);
            }
        });

        m_JButtonPlus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButtonPlus.setText("+");
        m_JButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButtonPlusActionPerformed(evt);
            }
        });

        m_JButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButton4.setText("4");
        m_JButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButton4ActionPerformed(evt);
            }
        });

        m_JButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButton5.setText("5");
        m_JButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButton5ActionPerformed(evt);
            }
        });

        m_JButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButton6.setText("6");
        m_JButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButton6ActionPerformed(evt);
            }
        });

        m_JButtonMinus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButtonMinus.setText("-");
        m_JButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButtonMinusActionPerformed(evt);
            }
        });

        m_JButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButton7.setText("7");
        m_JButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButton7ActionPerformed(evt);
            }
        });

        m_JButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButton8.setText("8");
        m_JButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButton8ActionPerformed(evt);
            }
        });

        m_JButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButton9.setText("9");
        m_JButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButton9ActionPerformed(evt);
            }
        });

        m_JButtonMultiply.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButtonMultiply.setText("*");
        m_JButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButtonMultiplyActionPerformed(evt);
            }
        });

        m_JButtonSquare.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButtonSquare.setText("√ ");
        m_JButtonSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButtonSquareActionPerformed(evt);
            }
        });

        m_JButtonClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButtonClear.setText("C");
        m_JButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButtonClearActionPerformed(evt);
            }
        });

        m_JButtonRemainder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButtonRemainder.setText("%");
        m_JButtonRemainder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButtonRemainderActionPerformed(evt);
            }
        });

        m_JButtonDivide.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JButtonDivide.setText("/");
        m_JButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_JButtonDivideActionPerformed(evt);
            }
        });

        m_JTextPaneResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_JTextPaneResult.setText("0");
        m_JTextPaneResult.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        m_JTextPaneResult.setEnabled(false);
        m_JTextPaneResult.setVerifyInputWhenFocusTarget(false);
        m_JScrollPane.setViewportView(m_JTextPaneResult);
        m_JTextPaneResult.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(m_JScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(m_JButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(m_JButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(m_JButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(m_JButtonSquare)
                                .addGap(18, 18, 18)
                                .addComponent(m_JButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(m_JButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(m_JButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(m_JButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(m_JButtonPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(m_JButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m_JButtonRemainder)
                                    .addComponent(m_JButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(m_JButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(m_JButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(m_JButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(m_JButtonDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_JButtonMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_JButtonMinus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_JButtonPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_JButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(m_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_JButtonSquare)
                    .addComponent(m_JButtonRemainder)
                    .addComponent(m_JButtonClear)
                    .addComponent(m_JButtonDivide))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_JButton7)
                    .addComponent(m_JButton8)
                    .addComponent(m_JButton9)
                    .addComponent(m_JButtonMultiply))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_JButton4)
                    .addComponent(m_JButton5)
                    .addComponent(m_JButton6)
                    .addComponent(m_JButtonMinus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_JButton1)
                    .addComponent(m_JButton2)
                    .addComponent(m_JButton3)
                    .addComponent(m_JButtonPlus))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_JButtonPlusMinus)
                    .addComponent(m_JButton0)
                    .addComponent(m_JButtonPoint)
                    .addComponent(m_JButtonEqual))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_JButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButton0ActionPerformed
        // TODO add your handling code here:
        if (!m_zeroFlag)
            m_JTextPaneResult.setText(m_JTextPaneResult.getText() + "0");
        
        
    }//GEN-LAST:event_m_JButton0ActionPerformed

    private void m_JButtonPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButtonPlusMinusActionPerformed
        // TODO add your handling code here:
        
        if(!m_zeroFlag)
        {
            if(m_negativeFlag)
                m_JTextPaneResult.setText(m_JTextPaneResult.getText().substring(0, 1).replace("",""));
            else
                m_JTextPaneResult.setText("-" + m_JTextPaneResult.getText());
            m_negativeFlag = !m_negativeFlag;
        }
        
        
    }//GEN-LAST:event_m_JButtonPlusMinusActionPerformed

    private void m_JButtonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButtonPointActionPerformed
        // TODO add your handling code here:
        if(!m_pointFlag)
            m_JTextPaneResult.setText( m_JTextPaneResult.getText() + ".");
        m_pointFlag = true;
    }//GEN-LAST:event_m_JButtonPointActionPerformed

    private void m_JButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButton1ActionPerformed
        // TODO add your handling code here:
        
        updateText(m_JButton1);
    }//GEN-LAST:event_m_JButton1ActionPerformed

    private void m_JButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButton2ActionPerformed
        // TODO add your handling code here:
        updateText(m_JButton2);
    }//GEN-LAST:event_m_JButton2ActionPerformed

    private void m_JButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButton3ActionPerformed
        // TODO add your handling code here:
        updateText(m_JButton3);
    }//GEN-LAST:event_m_JButton3ActionPerformed

    private void m_JButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButton4ActionPerformed
        // TODO add your handling code here:
        updateText(m_JButton4);
    }//GEN-LAST:event_m_JButton4ActionPerformed

    private void m_JButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButton5ActionPerformed
        // TODO add your handling code here:
        updateText(m_JButton5);
    }//GEN-LAST:event_m_JButton5ActionPerformed

    private void m_JButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButton6ActionPerformed
        // TODO add your handling code here:
        updateText(m_JButton6);
    }//GEN-LAST:event_m_JButton6ActionPerformed

    private void m_JButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButton7ActionPerformed
        // TODO add your handling code here:
        updateText(m_JButton7);
    }//GEN-LAST:event_m_JButton7ActionPerformed

    private void m_JButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButton8ActionPerformed
        // TODO add your handling code here:
        updateText(m_JButton8);
    }//GEN-LAST:event_m_JButton8ActionPerformed

    private void m_JButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButton9ActionPerformed
        // TODO add your handling code here:
        updateText(m_JButton9);
    }//GEN-LAST:event_m_JButton9ActionPerformed

    private void m_JButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButtonEqualActionPerformed
        // TODO add your handling code here:
        operate();
        m_operationFlag = true;
        m_lastOperator = '=';
    }//GEN-LAST:event_m_JButtonEqualActionPerformed

    private void m_JButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButtonPlusActionPerformed
        // TODO add your handling code here:
        operate();
        m_lastOperator = '+';
    }//GEN-LAST:event_m_JButtonPlusActionPerformed

    private void m_JButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButtonMinusActionPerformed
        // TODO add your handling code here:
        operate();
        m_lastOperator = '-';
    }//GEN-LAST:event_m_JButtonMinusActionPerformed

    private void m_JButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButtonMultiplyActionPerformed
        // TODO add your handling code here:
        operate();
        m_lastOperator = '*';
    }//GEN-LAST:event_m_JButtonMultiplyActionPerformed

    private void m_JButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButtonDivideActionPerformed
        // TODO add your handling code here:
        operate();
        m_lastOperator = '/';
    }//GEN-LAST:event_m_JButtonDivideActionPerformed

    private void m_JButtonSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButtonSquareActionPerformed
        // TODO add your handling code here:
        
        double result;
        
        result = Math.sqrt(Double.valueOf(m_JTextPaneResult.getText()));
        String text = String.valueOf(result);
        m_JTextPaneResult.setText(text);
        
    }//GEN-LAST:event_m_JButtonSquareActionPerformed

    private void m_JButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButtonClearActionPerformed
        // TODO add your handling code here:
        m_zeroFlag = true;
        m_operationFlag = false;
        m_JTextPaneResult.setText("0");
    }//GEN-LAST:event_m_JButtonClearActionPerformed

    private void m_JButtonRemainderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_JButtonRemainderActionPerformed
        // TODO add your handling code here:
        operate();
        m_lastOperator = '%';
    }//GEN-LAST:event_m_JButtonRemainderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton m_JButton0;
    private javax.swing.JButton m_JButton1;
    private javax.swing.JButton m_JButton2;
    private javax.swing.JButton m_JButton3;
    private javax.swing.JButton m_JButton4;
    private javax.swing.JButton m_JButton5;
    private javax.swing.JButton m_JButton6;
    private javax.swing.JButton m_JButton7;
    private javax.swing.JButton m_JButton8;
    private javax.swing.JButton m_JButton9;
    private javax.swing.JButton m_JButtonClear;
    private javax.swing.JButton m_JButtonDivide;
    private javax.swing.JButton m_JButtonEqual;
    private javax.swing.JButton m_JButtonMinus;
    private javax.swing.JButton m_JButtonMultiply;
    private javax.swing.JButton m_JButtonPlus;
    private javax.swing.JButton m_JButtonPlusMinus;
    private javax.swing.JButton m_JButtonPoint;
    private javax.swing.JButton m_JButtonRemainder;
    private javax.swing.JButton m_JButtonSquare;
    private javax.swing.JScrollPane m_JScrollPane;
    private javax.swing.JTextPane m_JTextPaneResult;
    // End of variables declaration//GEN-END:variables

    private void updateText(JButton mf_JButton) {
        if (m_operationFlag) 
        {
            m_JTextPaneResult.setText("");
            m_operationFlag = false;
        }
        if (m_zeroFlag)
        {
            m_JTextPaneResult.setText(mf_JButton.getText());
            m_zeroFlag = false;
        }
        else 
            m_JTextPaneResult.setText(m_JTextPaneResult.getText() + mf_JButton.getText());
    }

    private void operate() 
    {
        double val;
        
        if (m_lastOperator == '=')
            m_result = Double.valueOf(m_JTextPaneResult.getText());
        else 
        {
            val = Double.valueOf(m_JTextPaneResult.getText());
            switch (m_lastOperator) 
            {
                case '+':
                    m_result += val;
                    break;
                case'-':
                    m_result -= val;
                    break;
                case '*':
                    m_result *= val;
                    break;
                case '/':
                    m_result /= val;
                    break;
                case '%':
                    m_result %= val;
                    break;
            }
        }
        
        m_JTextPaneResult.setText(String.valueOf(m_result));
        m_operationFlag = true;
        m_pointFlag = false;
        
    }

}
